#pragma once

#include <cstdint>

enum class Opcode : uint8_t {
    PushInt,
    PushFloat,
    PushConst,
    AddInt,
    SubInt,
    MultInt,
    DivInt,
    AddFloat,
    SubFloat,
    MultFloat,
    DivFloat,
    StoreInt,
    StoreFloat,
    StoreConst,
    AddStrPtr,
    StoreStrPtr,
    PrintInt,
    PrintStrPtr,
    PrintFloat,
    LoadFloat,
    LoadInt,
    LoadStrPtr,
    FloatToStrPtr,
    IntToFloat,
    IntToStrPtr,
    PushBool,
    StoreBool,
    PrintBool,
    LoadBool,
    IsEqInt,
    IsEqFloat,
    IsEqBool,
    IsGreaterFloat,
    IsGreaterInt,
    IsGreaterOrEqFloat,
    IsGreaterOrEqInt,
    IsLessOrEqFloat,
    IsLessOrEqInt,
    IsLessFloat,
    IsLessInt,
    JmpIfFalse,
    IsNotEqInt,
    IsNotEqFloat,
    IsNotEqBool,
    Jmp,
    JmpBack,
    PopStack
};